name: Deploy Demo Website

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'demo/**'

jobs:
  master-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build Website
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_NAME: pengxiaotian
          GIT_CONFIG_EMAIL: 673923162@qq.com
          COMMIT_MESSAGE: website deploy
